# NN with backpropagation


In [58]:
import numpy as np
x = [[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],
[0,0,0,0,1,0,0,0],[0,0,0,0,0,1,0,0],[0,0,0,0,0,0,1,0],[0,0,0,0,0,0,0,1]]
x_array = np.array(x)
X_train = x_array[0:6]
print(X_train)
X_test = x_array[7:8]
Y = x_array
#print(Y)

# We need to have 8 inputs (each number in a row of the matrix),a hidden layer with 3 nodes + bias and an output layer with 8 nodes

n_input = 8 # We need to have 8 inputs (each number in a row of the matrix)
n_hidden = 3
n_output = 8
# Weights
np.random.seed(42)
W1 = np.random.rand(n_input, n_hidden) # 8 x 3 Weights for input to hidden
#print(W1)
W2 = np.random.rand(n_hidden, n_output) # 3 x 8 Weights for hidden to output
#print(W2)
# Biases
b1 = np.random.rand(n_hidden) # Bias for hidden layer (3)
b2 = np.random.rand(n_output) # Bias for output layer (8)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def first_layer(X):
    return sigmoid(np.dot(X, W1) + b1)

def second_layer(hidden_output):
    return sigmoid(np.dot(hidden_output, W2) + b2)

second_layer_output_0 = second_layer(first_layer(X_train))
#print(second_layer_output_0)
# def sigmoid_derivative(x):
#     return x * (1 - x)
for i in range(1000): # Training loop
    # Forward pass
    batches = np.array_split(X_train, 3)
    Y_batches = np.array_split(Y[0:6], 3)
    for X_batch, Y_batch in zip(batches, Y_batches):
        hidden_output = first_layer(X_batch)
        output = second_layer(hidden_output)
        #print("Output after iteration", i, ":", output)
        # Compute loss (Mean Squared Error)
        loss_value = ((Y_batch - output) ** 2)

        
        # Backpropagation
        output_error = Y_batch - output
        output_delta = output_error * (output * (1 - output))
        
        hidden_error = output_delta.dot(W2.T)
        hidden_delta = hidden_error * (hidden_output * (1 - hidden_output))
        
        # Update weights and biases
        W2 += hidden_output.T.dot(output_delta)
        b2 += np.sum(output_delta, axis=0)
        W1 += X_batch.T.dot(hidden_delta)
        b1 += np.sum(hidden_delta, axis=0)
        if i % 100 == 0:
            print("Loss after iteration", i, ":", loss_value)
            print ("Batch:", X_batch)

    

def loss(Y, second_layer_output_0):
    return ((Y - second_layer_output_0) ** 2)
#loss_value = loss(Y[0:6], second_layer_output_0)
#print("Loss:", loss_value[0])

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]
Loss after iteration 0 : [[0.04930263 0.87100017 0.73591582 0.83295882 0.73538161 0.46304904
  0.64656094 0.51715703]
 [0.60454338 0.00615453 0.70068792 0.80172282 0.72468707 0.44085469
  0.61544978 0.4832863 ]]
Batch: [[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]]
Loss after iteration 0 : [[0.5258476  0.83494169 0.05646848 0.74150613 0.58164012 0.24006663
  0.42922685 0.28339418]
 [0.54077816 0.82687863 0.53489088 0.02086553 0.59044469 0.24441432
  0.41772433 0.27280637]]
Batch: [[0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]
Loss after iteration 0 : [[0.3327985  0.75764808 0.47139635 0.66418382 0.13953857 0.11206628
  0.21932923 0.12704762]
 [0.32157358 0.74799631 0.47419277 0.6671279  0.38010425 0.42649442
  0.21238363 0.13314764]]
Batch: [[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]
Loss after iteration 100 : [[7.38813915e-01 2.65954976e-02 1.13403927e-02 4.37755639e-02
  1.09171464e-02 8.584