# NN with backpropagation


In [ ]:
import numpy as np
x = [[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],
[0,0,0,0,1,0,0,0],[0,0,0,0,0,1,0,0],[0,0,0,0,0,0,1,0],[0,0,0,0,0,0,0,1]]
X = np.array(x)
Y = X
print(Y)

# We need to have 8 inputs (each number in a row of the matrix),a hidden layer with 3 nodes + bias and an output layer with 8 nodes

n_input = 8 # We need to have 8 inputs (each number in a row of the matrix)
n_hidden = 3
n_output = 8
# Weights
np.random.seed(42)
W1 = np.random.rand(n_input, n_hidden) # 8 x 3 Weights for input to hidden
#print(W1)
W2 = np.random.rand(n_hidden, n_output) # 3 x 8 Weights for hidden to output
#print(W2)
# Biases
b1 = np.random.rand(n_hidden) # Bias for hidden layer (3)
b2 = np.random.rand(n_output) # Bias for output layer (3)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def first_layer(X):
    return sigmoid(np.dot(X, W1) + b1)

def second_layer(hidden_output):
    return sigmoid(np.dot(hidden_output, W2) + b2)

second_layer_output_0 = second_layer(first_layer(X))
print(second_layer_output_0)
# def sigmoid_derivative(x):
#     return x * (1 - x)

def loss(Y, second_layer_output):
    return np.mean((Y - second_layer_output) ** 2)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
[[0.77795804 0.9332739  0.85785536 0.91266578 0.85754394 0.68047707
  0.80409013 0.71913631]
 [0.77752388 0.92154919 0.83707103 0.89538976 0.85128554 0.6639689
  0.78450607 0.69518796]
 [0.77194598 0.92826646 0.85420174 0.90739997 0.85131723 0.67686419
  0.7947783  0.71345235]
 [0.78118165 0.9245895  0.8337584  0.90366505 0.85532544 0.68085693
  0.78891424 0.70582937]
 [0.78092912 0.92486814 0.83995936 0.89871283 0.85494243 0.66538212
  0.79039891 0.69842299]
 [0.77257349 0.92143406 0.83973377 0.89923105 0.84836503 0.67293418
  0.78325008 0.70222266]
 [0.77694793 0.92457498 0.84078819 0.90242834 0.85258139 0.6752445
  0.78887502 0.70516499]
 [0.77122603 0.91977754 0.83898523 0.89648469 0.8466765  0.66913055
  0.78058738 0.69889458]]
