# NN with backpropagation


In [ ]:
import numpy as np
x = [[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],
[0,0,0,0,1,0,0,0],[0,0,0,0,0,1,0,0],[0,0,0,0,0,0,1,0],[0,0,0,0,0,0,0,1]]
X = np.array(x)
Y = X
print(Y)

# We need to have 8 inputs (each number in a row of the matrix),a hidden layer with 3 nodes + bias and an output layer with 8 nodes

n_input = 8 # We need to have 8 inputs (each number in a row of the matrix)
n_hidden = 3
n_output = 8
# Weights
np.random.seed(42)
W1 = np.random.rand(n_input, n_hidden) # 8 x 3 Weights for input to hidden
print(W1)
W2 = np.random.rand(n_hidden, n_output) # 3 x 8 Weights for hidden to output
print(W2)
# Biases
b1 = np.random.rand(n_hidden) # Bias for hidden layer (3)
b2 = np.random.rand(n_output) # Bias for output layer (3)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))




# def sigmoid_derivative(x):
#     return x * (1 - x)


[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]]
[[0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041
  0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735 0.30461377 0.09767211
  0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998 0.66252228
  0.31171108 0.52006802]]
